### PR TITLE
WIP: Adds ability to set alternate local folder for config/metadata directory

### LINKED ISSUE #108: Ability to specifiy alternate local config location
Currently config/metadata options are folder in repository or remote metadata repository integration. This adds the option to have an alternative local local folder for config and metadata .json files.

### PR DESCRIPTION
**Pull request by cfleur**
WIP!

Closes #108

Based on v1.3.2 due to problems running retrievals on v1.4.0 (see #107).

 Config directory is specified in config_setup.yml.

Includes cherry pick of [Use sys.executable instead of .venv/bin/python to run retrievals](https://github.com/tum-esm/em27-retrieval-pipeline/commit/0af30503f1826da5c0add8acfb29b0e7233cc347)

### CODE REVIEW

**Comment by cfleur** [comment]
@dostuffthatmatters do you have any comments on this?
TODO: clean up repeated code, maybe something else

**Comment by dostuffthatmatters** [comment]
This is a great idea! We actually just started a second metadata repository because one of our measurement campaigns produced so much metadata.

I would prefer if one passes the alternative config directory via the command line instead of a separate `config_setup.yaml` file.

What do you think?

**Comment by cfleur** [comment]
@dostuffthatmatters I tested the fix for pressure null values #107 and its working. I will rebase this to the latest updates.
Regarding specifying the location for the folder. I thought about this and think it would be nice to have this set as an environment variable. I think the command line arguments can get a little messy. Especially depending how one is calling the pipeline, it might get long. What do you think? Then the user can set the environment variable however they want.

**Comment by dostuffthatmatters** [comment]
@cfleur agreed - environment variables is a good way of doing it.

**Comment by cfleur** [comment]
Closing as PR #111 opened instead from different branch.

**Pull request closed without merging**
